// <auto-generated />
using System;
using E_Commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Migrations
{
    [DbContext(typeof(JumaContext))]
    [Migration("20211231224153_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CustomersViewModelOrders", b =>
                {
                    b.Property<string>("CustomersCustomerName")
                        .HasColumnType("nvarchar (30)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INT");

                    b.HasKey("CustomersCustomerName", "OrderNumber");

                    b.HasIndex("OrderNumber");

                    b.ToTable("CustomersViewModelOrders");
                });

            modelBuilder.Entity("E_Commerce.Models.Customers", b =>
                {
                    b.Property<string>("CustomerName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar (30)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.Property<string>("CustomersViewModelCustomerName")
                        .HasColumnType("nvarchar (30)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.HasKey("CustomerName");

                    b.HasIndex("CustomersViewModelCustomerName");

                    b.HasIndex(new[] { "Address" }, "Address");

                    b.HasIndex(new[] { "CustomerName" }, "CustomerName");

                    b.HasIndex(new[] { "EmailAddress" }, "EmailAddress");

                    b.HasIndex(new[] { "PhoneNumber" }, "PhoneNumber");

                    b.HasIndex(new[] { "PostCode" }, "PostCode");

                    b.ToTable("Customers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Customers");
                });

            modelBuilder.Entity("E_Commerce.Models.Images", b =>
                {
                    b.Property<int>("ItemNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemNumber");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("E_Commerce.Models.Orders", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ImagesOrders", b =>
                {
                    b.Property<int>("ImageItemNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersOrderNumber")
                        .HasColumnType("INT");

                    b.HasKey("ImageItemNumber", "OrdersOrderNumber");

                    b.HasIndex("OrdersOrderNumber");

                    b.ToTable("ImagesOrders");
                });

            modelBuilder.Entity("E_Commerce.Models.CustomersViewModel", b =>
                {
                    b.HasBaseType("E_Commerce.Models.Customers");

                    b.ToTable("Customers");

                    b.HasDiscriminator().HasValue("CustomersViewModel");
                });

            modelBuilder.Entity("CustomersViewModelOrders", b =>
                {
                    b.HasOne("E_Commerce.Models.CustomersViewModel", null)
                        .WithMany()
                        .HasForeignKey("CustomersCustomerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce.Models.Orders", null)
                        .WithMany()
                        .HasForeignKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce.Models.Customers", b =>
                {
                    b.HasOne("E_Commerce.Models.CustomersViewModel", null)
                        .WithMany("Customers")
                        .HasForeignKey("CustomersViewModelCustomerName");
                });

            modelBuilder.Entity("ImagesOrders", b =>
                {
                    b.HasOne("E_Commerce.Models.Images", null)
                        .WithMany()
                        .HasForeignKey("ImageItemNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce.Models.Orders", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce.Models.CustomersViewModel", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
